spring:
  datasource:
    url: jdbc:mysql://localhost:3306/udemy-spring
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      javax:
        persistence:
          validation:
            mode: none
